on: [push, pull_request]

name: ci

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install
        run: npm install

      - name: Test
        run: npm run test
  release:
    name: Release to Github
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'axetroy/swagger2ts'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install
        run: npm install

      - name: Bump version
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          node ./script/bump.mjs

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          package: ./package.json
          token: ${{ secrets.NPM_TOKEN }}
